# Generated by Django 5.2.6 on 2025-10-03 13:58

import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Export",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=jobs.models.make_uuid,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Export",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("RUNNING", "RUNNING"),
                            ("COMPLETED", "COMPLETED"),
                            ("FAILED", "FAILED"),
                            ("TIMED_OUT", "TIMED_OUT"),
                        ],
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("image", "Image"), ("table", "Table")], max_length=32
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("gee", "Google Earth Engine"),
                            ("gdrive", "Google Drive"),
                            ("storage", "Google Cloud Storage"),
                        ],
                        max_length=255,
                    ),
                ),
                ("path", models.TextField()),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="GEE Task ID",
                    ),
                ),
                (
                    "task_status",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name="GEE Task Status",
                    ),
                ),
                ("error", models.TextField(blank=True, null=True)),
                ("next_check_at", models.DateTimeField()),
                ("lease_until", models.DateTimeField(blank=True, null=True)),
                ("poll_interval_sec", models.IntegerField(default=5)),
                ("attempts", models.IntegerField(default=0)),
                ("deadline_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "exports",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FileTransfer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("source_path", models.TextField(verbose_name="Source File")),
                ("destination_path", models.TextField(verbose_name="Destination File")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("MOVED", "Moved"),
                            ("NOT_MOVED", "Not Moved"),
                            ("ROLLED_BACK", "Rolled Back"),
                        ],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "file_transfers",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=jobs.models.make_uuid,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Job",
                    ),
                ),
                (
                    "job_status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "RUNNING"),
                            ("COMPLETED", "COMPLETED"),
                            ("FAILED", "FAILED"),
                        ],
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                (
                    "image_export_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("RUNNING", "RUNNING"),
                            ("COMPLETED", "COMPLETED"),
                            ("FAILED", "FAILED"),
                        ],
                        default="PENDING",
                        max_length=32,
                        verbose_name="Image Export Status",
                    ),
                ),
                (
                    "stats_export_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("RUNNING", "RUNNING"),
                            ("COMPLETED", "COMPLETED"),
                            ("FAILED", "FAILED"),
                        ],
                        default="PENDING",
                        max_length=32,
                        verbose_name="Stats Export Status",
                    ),
                ),
                (
                    "website_update_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("RUNNING", "RUNNING"),
                            ("COMPLETED", "COMPLETED"),
                            ("FAILED", "FAILED"),
                        ],
                        default="PENDING",
                        max_length=32,
                        verbose_name="Website Update Status",
                    ),
                ),
                (
                    "report_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("RUNNING", "RUNNING"),
                            ("COMPLETED", "COMPLETED"),
                            ("FAILED", "FAILED"),
                        ],
                        default="PENDING",
                        max_length=32,
                        verbose_name="Report Status",
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True, null=True, verbose_name="Error Messages"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC", max_length=32, verbose_name="Timezone"
                    ),
                ),
                ("created_at", models.DateTimeField(verbose_name="Created At")),
                ("updated_at", models.DateTimeField(verbose_name="Updated At")),
            ],
            options={
                "db_table": "jobs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Modis",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        choices=[("terra", "Terra"), ("aqua", "Aqua")], max_length=255
                    ),
                ),
                ("collection", models.CharField(max_length=255)),
                ("images", models.IntegerField()),
                ("last_image", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "modis",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("attempts", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "reports",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="WebsiteUpdate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                (
                    "pull_request_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "pull_request_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("attempts", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "website_updates",
                "managed": False,
            },
        ),
    ]
